name: PugRecon

on:
  workflow_dispatch:

permissions:
  contents: write
      
jobs:
  build-and-run:
    name: Build & Run SanicDNS
    runs-on: ubuntu-latest
    env:
      TERM: xterm    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          
      - name: Install system dependencies
        shell: bash
        run: |
          git clone https://github.com/c3l3si4n/pugdns
          cd pugdns
          sudo apt install linux-headers-$(uname -r) llvm libbpf-dev clang
          sudo ln -s /usr/include/x86_64-linux-gnu/asm /usr/include/asm
          go generate && go build

          
      - name: Install ethtool & shrink NIC queues
        run: |
          sudo apt-get update
          sudo apt-get install -y ethtool
          # If eth0 doesn’t exist, adjust the interface name accordingly
          sudo ethtool -L eth0 combined 3 || true          


      - name: Verify installation
        run: |
          echo "Current dir: $(pwd)"
          ls -lh ./pugdns
          realpath ./pugdns || readlink -f ./pugdns


      - name: Sanity-check PugDNS as runner user
        run: |
          echo "Running without sudo…"
          ./pugdns -h || true 

      - name: Debug PugDNS binary internals
        run: |
          file ./pugdns
          ldd ./pugdns || true
          find . -type f -executable -exec file {} \; | grep 'ELF'
          
          
      - name: Run PugDns against your lists
        run: |
           export TERM=xterm  
           cat navy_mil.txt | sed 's/$/.navy.mil/g'> wordlist.txt
           sudo bash -c "exec \"$GITHUB_WORKSPACE/pugdns/pugdns\" -interface eth0 -domains wordlist.txt -nameservers resolvers.txt -retries 15  -output out.json"
     
      - name: Upload logs and output
        uses: actions/upload-artifact@v4
        with:
          name: pugdns-results
          path: |
            out.json
            
